[WIP] MGMT-18578 - Add nmstatectl binary to initrd in minimal ISO for OCP 4.13-4.17 (x86_64 architecture)
openshift/assisted-image-service pull request #274
Opened 2024-08-22 14:36 UTC by linoyaslan

## Description

As part of integrating the nmstate service into our flow, it's necessary to include the `nmstatectl` binary in the initrd for minimal ISO cases. This ensures that the pre-network-manager-config service can run the nmstate service early during the boot process, allowing the nmstate YAML to be applied as keyfiles.

## How was this code tested?

To verify this, I used test-infra's Minikube, generated and downloaded the minimal ISO, then interrupted the boot process to confirm that the `nmstate.img` was successfully added to the initrd.

## Assignees

/cc @danielerez 
/cc @carbonin 
/cc @jhernand 
/cc @AlonaKaplan 

## Links

## Checklist

- [X] Title and description added to both, commit and PR
- [] Relevant issues have been associated
- [X] Reviewers have been listed
- [X] This change does not require a documentation update (docstring, `docs`, README, etc)
- [X] Does this change include unit tests (note that code changes require unit tests)

2024-08-22 14:41 UTC, linoyaslan commented
/test all

2024-08-22 15:15 UTC, jhernand commented
Putting the binary inside the repository and inside the image of the service may be problematic: it will be very hard to replace it if we find a bug, for example. I know that eventually it will be taken from the rootfs, but could we meanwhile take it from some configurable place outside of the image? For example, could we have a new `EXTRA_INITRD_FILES` environment pointing to a directory containing them? Maybe with sub-directories for different architectures? I mean something like this:

```
$ find "${EXTRA_INITRD_FILES}" -type f
.../x86_64/usr/bin/nmstatectl
.../arm64/usr/bin/nmstatectl
```

Then providing the files will be done when the service is deployed, not when it is built.

I'd also suggest to make this optional: if the variable isn't set then the behavior should be to not include the new initrd in the ISO. That will help with upgrades of existing environments.

Finally I'd suggest to give a more generic name to the initrd file, something like `extra.img`, because that way we can reuse it for other files not related to nmstate.

2024-08-22 16:16 UTC, danielerez commented
> Putting the binary inside the repository and inside the image of the service may be problematic: it will be very hard to replace it if we find a bug, for example. I know that eventually it will be taken from the rootfs, but could we meanwhile take it from some configurable place outside of the image? For example, could we have a new `EXTRA_INITRD_FILES` environment pointing to a directory containing them? Maybe with sub-directories for different architectures? I mean something like this:
> 
> ```
> $ find "${EXTRA_INITRD_FILES}" -type f
> .../x86_64/usr/bin/nmstatectl
> .../arm64/usr/bin/nmstatectl
> ```
> 
> Then providing the files will be done when the service is deployed, not when it is built.
> 
> I'd also suggest to make this optional: if the variable isn't set then the behavior should be to not include the new initrd in the ISO. That will help with upgrades of existing environments.
> 

Hey @jhernand, so with this approach it means we'd need to manually add the `nmstatectl` binary on SaaS, right? Which means one more thing to maintain :/
Maybe, as an alternative, for now we can simply amend the code to download the binary: https://github.com/nmstate/nmstate/releases/download/v2.2.35/nmstatectl-linux-x64.zip
It could be of course cached, as we do for the ISOs.
wdyt?

2024-08-22 17:36 UTC, carbonin commented
>Maybe, as an alternative, for now we can simply amend the code to download the binary: https://github.com/nmstate/nmstate/releases/download/v2.2.35/nmstatectl-linux-x64.zip

How does this work for disconnected on-prem installs?

2024-08-22 17:42 UTC, carbonin commented
If we're only doing x86 could we install the RPM in the container build and use that?
That would also allow us to take advantage of security scanning for images. Also on the security note I think it's generally not good practice to include non-source-based binaries in images. I'm not sure if anything in our build pipeline will block us though as I can't remember where I read this.

2024-08-22 17:44 UTC, carbonin commented
If not the RPM approach (and we don't plan the committed-binary to prod) is there some reason to not be doing the download in the container build where we would at least be able to see how the binary is downloaded and what version it is?

2024-08-22 19:17 UTC, jhernand commented
My understanding is that as @linoyaslan says in the description this is a temporary implementation to ease further development, and in the future (near future, I hope) we will change this code to extract the binary from the `rootfs.img` file. What I suggest is to let this pull request move forward, with the capability to enable/disable this functionality at will, and without including the binaries in the repository or the image.

Downloading the file in runtime like @danielerez suggests seems reasonable to me as well, as long we understand that is also a temporary implementation that can be enabled/disabled.

Installing the RPM, even if it is in the container build, also makes it hard to replace those files without upgrading the service, but it is better than having the binary in the repository.

Or maybe we should just wait till the `rootfs.img` implementation is ready?

2024-08-22 20:47 UTC, carbonin requested changes
We should also add the additional initrd in the isolinux case.

2024-08-22 20:47 UTC, carbonin commented on pkg/isoeditor/rhcos.go
> +		return []byte{}, err
You can use `nil` for the slice return value in an error case.

2024-08-22 20:47 UTC, carbonin commented on pkg/isoeditor/rhcos.go
> +	}
Can we create a helper for this? It's not something that I feel like should be repeated.

Maybe even create some way to dedupe even more of this function and [`Archive`](https://github.com/openshift/assisted-image-service/blob/180a34e65986e17b3ee16861ca40d64ae442f0d6/pkg/isoeditor/ignition.go#L15-L48)?

2024-08-26 18:16 UTC, linoyaslan commented
@jhernand @carbonin  I would appreciate your review again.

2024-09-01 06:27 UTC, linoyaslan commented
/all tests

2024-09-01 06:57 UTC, linoyaslan commented
/test [|all]

2024-09-01 06:57 UTC, linoyaslan commented
/test all

2024-09-08 08:01 UTC, danielerez commented on pkg/isoeditor/rhcos.go
> +	if err := editFile(foundGrubPath, `(?m)^(\s+initrd) (.+| )+$`, fmt.Sprintf("$1 $2 %s %s", ramDiskImagePath, nmstateDiskImagePath)); err != nil {
I think it should be added only if the nmstate disk image was generated. Boot would probably fail with a missing ram disk file.

2024-09-08 08:01 UTC, danielerez commented on pkg/isoeditor/rhcos.go
> +	if err := editFile(filepath.Join(extractDir, "isolinux/isolinux.cfg"), `(?m)^(\s+append.*initrd=\S+) (.*)$`, fmt.Sprintf("${1},%s,%s ${2}", ramDiskImagePath, nmstateDiskImagePath)); err != nil {
Same, should be added only if `nmstateDiskImagePath` exists.

2024-09-08 12:32 UTC, linoyaslan commented
/test all

2024-09-08 13:40 UTC, linoyaslan commented
/retest

2024-09-09 09:18 UTC, linoyaslan commented
/test edge-e2e-ai-operator-ztp

2024-09-09 18:39 UTC, carbonin reviewed
Few minor comments, otherwise looks good.

2024-09-09 18:39 UTC, carbonin commented on pkg/isoeditor/rhcos_test.go
> +			os.Remove(nmstatectlPath)
You should be removing the entire `extractDir` path here. Otherwise I think you'll end up leaking temp dirs.

2024-09-09 18:39 UTC, carbonin commented on pkg/isoeditor/rhcos.go
> +		return nil
I think this is a bit unexpected.

I'd rather `createNmstateRamDisk` fail if it doesn't ... create the nmstate ram disk :shrug: 

I'd say do this arch check in the caller and either don't call this function at all or error when the architecture doesn't match.

2024-09-10 12:03 UTC, linoyaslan commented
/test edge-lint

2024-09-10 14:19 UTC, linoyaslan commented
/test edge-lint

2024-09-10 16:55 UTC, merged